### ISSUE TITLE
Summing uvfits files doesn't produce expected results

### ISSUE THREAD

**Issue by zakiali** [HERA-Team/pyuvdata#254] opened 2017-10-19 21:54 UTC
I am trying to comgine uvfits files (omnical mdl files) together by summing the UVData objects together (code below). The result doesn't make sense to me and it looks like only the first file is being preserved. I can however individually read files and concatenate individual baseline data together in a new array to produce correct results.

Code:
`init_mdl = pyuvdata.UVData()`
`init_mdl.read_uvfits(mdl_data_file[0])`
`init_mdl.unphase_to_drift()`
`for mdl_file in mdl_data_file[1:]:`
`      uvmdl = pyuvdata.UVData()`
`      uvmdl.read_uvfits(mdl_file)`
`      uvmdl.unphase_to_drift()`
`      init_mdl += uvmdl`

![image](https://user-images.githubusercontent.com/940272/31796059-fce771de-b4dc-11e7-910a-cbda8d1124ce.png)

**Comment by adampbeardsley** [comment] 2017-10-19 22:16
What is an mdl file?
Presumably you're plotting an amplitude waterfall? Can you show what each file looks like individually, and the code for producing the plot?
Are these files anywhere that I can access to reproduce the problem?

**Comment by zakiali** [comment] 2017-10-19 22:47
I meant 'vis.uvfits' files (the model visibilities for a redundant baseline). 
That was actually the phase. You see the same thing in amp too.
You can find the data files at the path in the glob on lustre at nrao. Let me know if you have issues accessing that and I can put them somewhere else. 



```mdl_data_files = glob.glob('/lustre/aoc/projects/hera/zali/HERA2015/2457702/IDR3/zen.2457702.4[5-6]*.HH.uvc.vis.uvfits')
concat_array = []

init_mdl = pyuvdata.UVData()
init_mdl.read_uvfits(mdl_data_files[0])
init_mdl.unphase_to_drift()

concat_array = init_mdl.get_data(9, 20, 'xx')

for mdl_file in mdl_data_files[1:]:
    uvmdl = pyuvdata.UVData()
    uvmdl.read_uvfits(mdl_file)
    uvmdl.unphase_to_drift()
    
    # concatenate
    concat_array = np.concatenate([concat_array, uvmdl.get_data(9, 20, 'xx')])
    init_mdl += uvmdl


plt.figure()
plt.subplot(221)
uvtools.plot.waterfall(init_mdl.get_data(9,20,'xx'), mode='phs', cmap='inferno')
plt.xlabel('freq bin')
plt.ylabel('integration number')
plt.title('phs')
plt.subplot(222)
uvtools.plot.waterfall(concat_array, mode='phs', cmap='inferno')
plt.xlabel('freq bin')
plt.ylabel('integration number')
plt.title('phs')
plt.subplot(223)
uvtools.plot.waterfall(init_mdl.get_data(9,20,'xx'), mode='log', mx=0, drng=3, cmap='inferno')
plt.xlabel('freq bin')
plt.ylabel('integration number')
plt.title('log amplitude')
plt.subplot(224)
uvtools.plot.waterfall(concat_array, mode='log', mx=0, drng=3, cmap='inferno')
plt.xlabel('freq bin')
plt.ylabel('integration number')
plt.title('log amplitude')

**Comment by adampbeardsley** [comment] 2017-10-19 23:09
Ok, I've been able to reproduce it on my end. It looks like there's some funny ordering stuff going on, but it's not immediately obvious. I'll try digging into it.

**Comment by adampbeardsley** [comment] 2017-10-21 12:57
@zakiali I think I figured out what's going wrong - there is a bug in the way pyuvdata concatenates the arrays, which is only exposed when the files have ordering where time is not the slowest axis. I pushed a branch, `bug_fix_add`, which I think fixes it but breaks other tests. My suspicion is that  the tests themselves aren't careful enough, and need updating.
Anyway, could you try that branch on your data and let me know if it fixes your problem? Then I'll fix up the tests and add some new ones.

**Comment by zakiali** [comment] 2017-10-23 18:05
@adampbeardsley This does seem to fix my problem. Thanks for looking into this!

**Comment by adampbeardsley** [comment] 2017-11-02 21:57
@zakiali So it turned out I still had a bug in this branch, which caused some data to be zeroed. I believe I fixed it, but could you check your case again to be sure? I rebased the branch, so you will have to delete your local branch and re-pull it. Thanks!

**Comment by bhazelton** [comment] 2017-11-28 21:31
Is this fixed with the referenced PR?

**Comment by adampbeardsley** [comment] 2017-11-28 21:32
Yup

**Closed by adampbeardsley** 2017-11-28 21:32 UTC
